### ISSUE TITLE
Submit to AUR

### ISSUE THREAD

**Issue by G-Pereira** [giscan/Beremiz-arch#1]
Why don't you put this in AUR packages?

**Comment by kikislater** [comment]
Good question ! 
Answer is that I have to take time on how to put in AUR ;-)

**Comment by AndreySV** [comment]
Someone've done some work to put Beremiz in AUR already.
https://aur.archlinux.org/packages/beremiz-hg/
https://aur.archlinux.org/packages/matiec-hg/

**Comment by kikislater** [comment]
Thank you AndreySV. It was done after G-Pereira answering !
Could be close now
